# Generated by Django 3.2.6 on 2021-09-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
