# Generated by Django 3.2.6 on 2021-09-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0002_auto_20210902_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblock',
            old_name='content',
            new_name='sub_content',
        ),
    ]
