# Generated by Django 3.2.6 on 2021-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
