# Generated by Django 3.2.6 on 2021-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0003_rename_content_contentblock_sub_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
