# Generated by Django 3.2.6 on 2021-09-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0004_contentblock_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentbock', to='pytutorial.post'),
        ),
    ]
