# Generated by Django 3.2.6 on 2021-09-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0005_alter_contentblock_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
