# Generated by Django 3.2.6 on 2021-09-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0006_remove_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentblocks', to='pytutorial.post'),
        ),
    ]
