# Generated by Django 3.2.6 on 2021-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0007_alter_contentblock_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
