# Generated by Django 3.2.6 on 2021-09-13 08:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0008_auto_20210909_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='sub_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
