# Generated by Django 3.2.6 on 2021-09-13 08:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0009_auto_20210913_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='sub_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
