# Generated by Django 3.2.6 on 2021-09-13 18:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0011_alter_contentblock_sub_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='sub_content',
            field=django_quill.fields.QuillField(),
        ),
    ]
