# Generated by Django 3.2.6 on 2021-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytutorial', '0012_alter_contentblock_sub_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
